### ISSUE TITLE
Consider possibility to pass whole app object as parameter

### ISSUE THREAD

**Issue by krasnoludkolo** [javalin/javalin-test#3]
I'm wondering if such api is possible?
`fun run(app:Javalin, consumer: (Javalin, Client) -> Unit)`

I found it useful to be able to test the entire application, not just one handler. 

If it is approved I can try to prepare such PR

**Comment by oharaandrew314** [comment]
Hey @krasnoludkolo, I have my apps configured with dependency injection in mind.  So my tests pass the `Javalin` instance into the function that configures it.

```
JavalinTest.test { app, client ->
    MyServer(app, dependencies...)
    //perform test
}
```

Having said that, I can see the appeal of what you'd like to do.  I think it would simplify some of my tests that require injecting behaviour into `Javalin.create`.  You can be my guest to create a PR, but I might work on it if I have the chance later.  I think that we'll remove the ability to inject a `configurator: Consumer<JavalinConfig>` into the `JavalinTest` constructor, and replace the constructor arguments with an optional `Javalin` instance.

**Comment by oharaandrew314** [comment]
@krasnoludkolo let me know if the PR I just created suits your needs.

**Comment by krasnoludkolo** [comment]
Wow, thanks for really quick response. New api look great, that's what I had in mind. When can I expect the release of the new version?

**Comment by oharaandrew314** [comment]
@krasnoludkolo [0.4.0](https://jitpack.io/#javalin/javalin-test/0.4.0) is now available

**Comment by krasnoludkolo** [comment]
Thanks for info
